# Generated by Django 3.1.5 on 2021-01-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='landscape',
            field=models.BooleanField(default=False),
        ),
    ]
